# gitzone docker
image: hosttoday/ht-docker-dbase:npmci
services:
  - docker:dind
variables:
  DOCKER_DRIVER: overlay


stages:
  - build
  - test
  - release
  - trigger
  - pages

before_script:
  - yarn global add npmci
  - npmci docker prepare

build:
  stage: build
  script:
    - npmci docker build
  tags:
    - lossless
    - priv
  

test:
  stage: test
  script:
    - npmci docker test
  tags:
    - lossless
    - priv

release:
  stage: release
  script:
    - npmci docker
  only:
    - tags
    - triggers
  tags:
    - lossless
    - priv

trigger:
  stage: trigger
  script:
    - npmci trigger
  only:
    - tags
    - triggers
  tags:
    - lossless
    - priv

pages:
  before_script:
    - 'npmci -v'
  image: hosttoday/ht-docker-node:npmci
  stage: pages
  script:
    - npmci command yarn global add npmpage
    - npmci command npmpage
  only:
    - tags
  tags:
    - docker
  artifacts:
    expire_in: 1 week
    paths:
    - public
