image: hosttoday/ht-docker-dbase
services:
  - docker:dind

stages:
  - build
  - buildtags
  - test
  - release

variables:
  CONTAINER_TEST_IMAGE: registry.gitlab.com/hosttoday/ht-docker-node:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: registry.gitlab.com/hosttoday/ht-docker-node:latest

before_script:
  - npm uninstall -g npmci
  - npm install -g npmci
  - npmci prepare docker


buildBASE:
  stage: build
  script:
    - docker build -t hosttoday/ht-docker-node:latest .
    - docker push hosttoday/ht-docker-node:latest
  tags:
    - dockerbuild

buildTAGS:
  stage: buildtags
  script:
    - docker build -t hosttoday/ht-docker-node:lts ./Dockerfile_lts
    - docker push hosttoday/ht-docker-node:lts
    - docker build -t hosttoday/ht-docker-node:stable ./Dockerfile_stable
    - docker push hosttoday/ht-docker-node:stable
    - docker build -t hosttoday/ht-docker-node:npmci ./Dockerfile_npmci
    - docker push hosttoday/ht-docker-node:npmci
    - docker build -t hosttoday/ht-docker-node:npmts ./Dockerfile_npmts
    - docker push hosttoday/ht-docker-node:npmts
    - docker build -t hosttoday/ht-docker-node:npmpage ./Dockerfile_npmpage
    - docker push hosttoday/ht-docker-node:npmpage
  tags:
    - dockerbuild
  

test:
  stage: test
  script:
    - docker version
  only:
    - master
  tags:
    - dockerbuild

release:
  stage: release
  script:
    - docker version
  only:
    - master
  tags:
    - dockerbuild