# gitzone docker
image: hosttoday/ht-docker-dbase:npmci
services:
  - docker:dind

stages:
  - buildAndTest
  - trigger
  - pages

before_script:
  - yarn global add npmci
  - npmci docker login

buildTest:
  stage: buildAndTest
  script:
    - npmci docker build
    - npmci docker test
  except:
    - tags
    - triggers
  tags:
    - lossless
    - priv

buildTestRelase:
  stage: buildAndTest
  script:
    - npmci docker build
    - npmci docker test
    - npmci docker push registry.gitlab.com test
    - npmci docker push registry.gitlab.com
    - npmci docker push docker.io
  only:
    - tags
    - triggers
  tags:
    - lossless
    - priv

trigger:
  stage: trigger
  script:
    - npmci trigger
  only:
    - tags
    - triggers
  tags:
    - lossless
    - priv

pages:
  before_script:
    - 'npmci -v'
  image: hosttoday/ht-docker-node:npmci
  stage: pages
  script:
    - npmci command yarn global add npmpage
    - npmci command npmpage
  only:
    - tags
  tags:
    - docker
  artifacts:
    expire_in: 1 week
    paths:
    - public
