image: hosttoday/ht-docker-dbase:latest
services:
  - docker:dind

stages:
  - build
  - test
  - release
  - trigger

before_script:
  - npm uninstall -g npmci
  - npm install -g npmci
  - npmci prepare docker


build:
  stage: build
  script:
    - npmci build docker
  tags:
    - lossless
    - priv
  

test:
  stage: test
  script:
    - npmci test docker
  only:
    - tags
    - triggers
  tags:
    - lossless
    - priv

release:
  stage: release
  script:
    - npmci publish docker
  only:
    - tags
    - triggers
  tags:
    - lossless
    - priv

trigger:
  stage: trigger
  script:
    - npmci trigger
  only:
    - tags
    - triggers
  tags:
    - lossless
    - priv
