image: docker:git
services:
  - docker:dind

stages:
  - test
  - release

variables:
  CONTAINER_TEST_IMAGE: registry.gitlab.com/hosttoday/ht-docker-node:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: registry.gitlab.com/hosttoday/ht-docker-node:latest

before_script:
  - docker login -u $DOCKERU -p $DOCKERP

test:
  stage: test
  script:
    - docker version
    - docker build -t $CONTAINER_TEST_IMAGE .
  only:
    - master
  tags:
    - dockerbuild

release:
  stage: release
  script:
    - docker version
    - docker build -t hosttoday/ht-docker-node:latest .
    - docker push hosttoday/ht-docker-node:latest
  only:
    - master
  tags:
    - dockerbuild