# gitzone docker
image: hosttoday/ht-docker-dbase:npmci
services:
  - docker:dind

stages:
  - buildAndTest
  - triggerPagesVerify

before_script:
  - npm install -g @shipzone/npmci
  - npmci docker login

buildTest:
  stage: buildAndTest
  script:
    - npmci docker build
    - npmci docker test
  except:
    - tags
    - triggers
  tags:
    - lossless
    - priv

buildTestRelase:
  stage: buildAndTest
  script:
    - npmci docker build
    - npmci docker test
    - npmci docker push registry.gitlab.com test
    - npmci docker push registry.gitlab.com
    - npmci docker push docker.io
  only:
    - tags
    - triggers
  tags:
    - lossless
    - priv

trigger:
  stage: triggerPagesVerify
  script:
    - npmci trigger
  only:
    - tags
    - triggers
  tags:
    - lossless
    - priv

pages:
  stage: triggerPagesVerify
  before_script:
    - 'npmci -v'
  image: hosttoday/ht-docker-node:npmci
  script:
    - npmci command npm install -g npmpage
    - npmci command npmpage
  only:
    - tags
  tags:
    - docker
  artifacts:
    expire_in: 1 week
    paths:
    - public

verify:
  stage: triggerPagesVerify
  script:
    - npmci docker pull registry.gitlab.com test
  only:
    - tags
  tags:
    - docker