FROM hosttoday/ht-docker-node:latest

RUN bash -c "source $NVM_DIR/nvm.sh \
    && nvm install $NODE_VERSION_LTS \
    && nvm alias default $NODE_VERSION_LTS \
    && nvm use default \
    && npm install -g npm"
    
ENV NODE_PATH $NVM_DIR/v$NODE_VERSION_LTS/lib/node_modules
ENV PATH      $NVM_DIR/versions/node/v$NODE_VERSION_LTS/bin:$PATH