FROM hosttoday/ht-docker-node:npmci
RUN npmci install stable && npmci command npm install -g npmts && npmts -v \
    npmci install legacy && npmci command npm install -g npmts && npmts -v \
    npmci install lts && npmci command npm install -g npmts && npmts -v
