FROM hosttoday/ht-docker-node:stable
RUN apt-get update && apt-get install -y python-pip
RUN npmci command yarn global add npmpage
RUN pip install --upgrade pip \
    && pip install mkdocs \
    && mkdocs --version \
    && pip install mkdocs-material \
    && pip install pygments \
    && pip install pymdown-extensions

# Set working directory
WORKDIR /docs

# Expose MkDocs development server port
EXPOSE 8000

# Start development server by default
ENTRYPOINT ["mkdocs"]
CMD ["serve", "--dev-addr=0.0.0.0:8000"]