FROM hosttoday/ht-docker-node:npmci
RUN npmci install stable && npm install -g npmts && npmts -v \
    npmci install legacy && npm install -g npmts && npmts -v \
    npmci install lts && npm install -g npmts && npmts -v
